const state = { mode: 'request', inputs: { iso: '', tlv: '', de: '' } };
const $ = id => document.getElementById(id);
const input = $('input');
const output = $('output');
const packetTitle = $('packetTitle');
const meta = $('meta');
const p2peMode = $('p2peMode');

const FIELDS = {2:['PAN / Mobile','FIXED',8],3:['Processing Code','BCD',3],4:['Transaction Amount','BCD',6],6:['DCC final amount','BCD',6],7:['Server Transmission Date And Time','BCD',5],10:['DCC Conversion detail','BCD',4],11:['STAN','BCD',3],12:['Local Transaction Time / Date Time','BCD_DYNAMIC',0],13:['Local Transaction Date','BCD',2],14:['Expiry Date','BCD',2],15:['Settlement Date','BCD',2],17:['Effective Date','BCD',2],22:['POS Code','BCD',2],23:['Address/Application Sequence Number','BCD',3],24:['Destination NII (Network International Identifier)','BCD',2],30:['Original Amount','BCD',6],31:['Acquirer Ref No','LLVAR',1],32:['Acquiring Institution Id Code','LLVAR',1],35:['Track2','LLVAR',2],37:['Retrieval Reference Number','FIXED',12],38:['Approval Code','FIXED',12],39:['Response Code','FIXED',2],41:['TID','BYTE',8],42:['MID','BYTE',15],43:['Unique Txn ID','LLVAR',2],44:['Additional Response Data','LLVAR',2],45:['Track1','LLVAR',2],46:['KSN details','LLVAR',2],47:['User Id, Customer Id','LLVAR',2],48:['Connection code and date time stamp','LLVAR',2],49:['Transaction Currency Code','BCD',2],51:['Cardholder currency code','BCD',2],52:['Pin Block','BYTE',8],53:['CVV / AES PIN Block','LLVAR_DYNAMIC',0],54:['Additional Amount','LLVAR',2],55:['ICC Data','LLVAR',2],56:['Previous ROC, Date, Time in Reversal case','LLVAR_DYNAMIC',0],57:['Track2 Encrypted','LLVAR',2],58:['Card Indicator and Response Message','LLVAR',2],59:['DCC detail / RSA Key in Request, Advice in response','LLVAR',2],60:['Batch No','LLVAR',2],61:['Bank Details','LLVAR',2],62:['Invoice No','LLVAR',2],63:['Promo Details','LLVAR',2]};
window.FIELDS=FIELDS;
const SPECIAL_DE56=new Set(['982002','982004','960321']);
function cleanHex(v){return String(v||'').replace(/\s+/g,'').replace(/0x/gi,'').toUpperCase()}
function validHex(v){return /^[0-9A-F]*$/.test(v)&&v.length%2===0}
function hexBytes(h){const r=[];for(let i=0;i<h.length;i+=2)r.push(parseInt(h.slice(i,i+2),16));return r}
function ascii(h){return hexBytes(h).map(b=>b>=32&&b<=126?String.fromCharCode(b):'.').join('')}
function bcd(h){return h.replace(/F/gi,'')}
function bitmapBits(h){return hexBytes(h).map(b=>b.toString(2).padStart(8,'0')).join('')}
function activeFields(b){const bits=bitmapBits(b),r=[];for(let i=0;i<bits.length;i++)if(bits[i]==='1')r.push(i+1);return r}
function packetPrefix(hex,response){return response?{length:'',tpdu:hex.slice(0,10),mti:hex.slice(10,14),bitmapStart:14}:{length:hex.slice(0,4),tpdu:hex.slice(4,14),mti:hex.slice(14,18),bitmapStart:18}}
function fieldInfo(n,request,pc){const base=FIELDS[n];if(!base)return[`Field ${n}`,'LLVAR',2];let[name,type,len]=base;if(n===12)return[name,'BCD',request?3:6];if(n===46&&!p2peMode.checked)return[name,'UNSUPPORTED',0];if(n===53)return[p2peMode.checked?'AES PIN Block':'CVV','LLVAR',p2peMode.checked?1:2];if(n===56)return[name,'LLVAR',request&&!SPECIAL_DE56.has(pc)?1:2];return[name,type,len]}
function readPacket(hex,response){const p=packetPrefix(hex,response);let pos=p.bitmapStart;if(pos+16>hex.length)throw new Error('Bitmap is incomplete');let bitmap=hex.slice(pos,pos+16);pos+=16;if(parseInt(bitmap.slice(0,2),16)&0x80){if(pos+16>hex.length)throw new Error('Secondary bitmap is incomplete');bitmap+=hex.slice(pos,pos+16);pos+=16}return{...p,bitmapHex:bitmap,active:activeFields(bitmap),rest:hex.slice(pos)}}
function parseFields(hex,active,response){let pos=0,pc='',rows=[],error=null;for(const n of active){if(n===1)continue;const[name,type,len]=fieldInfo(n,!response,pc);if(type==='UNSUPPORTED'){error=`DE ${n} is not configured in Android parser (enable P2PE for DE46)`;break}try{let valueHex='',lengthInfo='',lengthHex='',declaredLength=null;if(type==='LLVAR'||type==='LLVAR_DYNAMIC'){const lc=len*2;if(pos+lc>hex.length)throw new Error(`DE ${n} length is incomplete`);const tag=hex.slice(pos,pos+lc);pos+=lc;if(!/^\d+$/.test(tag))throw new Error(`DE ${n} has invalid LLVAR length: ${tag}`);declaredLength=parseInt(tag,10);const vc=declaredLength*2;if(pos+vc>hex.length)throw new Error(`DE ${n} value is incomplete (declared ${declaredLength} bytes)`);valueHex=hex.slice(pos,pos+vc);pos+=vc;lengthHex=tag;lengthInfo=tag}else{const vc=len*2;if(pos+vc>hex.length)throw new Error(`DE ${n} value is incomplete`);valueHex=hex.slice(pos,pos+vc);pos+=vc;lengthInfo=len}rows.push({n,name,type,valueHex,lengthInfo,lengthHex,declaredLength});if(n===3)pc=bcd(valueHex)}catch(e){error=e.message||String(e);break}}return{rows,pos,remaining:hex.slice(pos),processingCode:pc,error}}
function parseIso(hex,response=false){const p=readPacket(hex,response);return{...p,...parseFields(p.rest,p.active,response)}}
function parseTlv(hex){const rows=[];let pos=0;while(pos+4<=hex.length){let tag=hex.slice(pos,pos+2);pos+=2;if((parseInt(tag,16)&31)===31)while(pos+2<=hex.length&&(parseInt(hex.slice(pos-2,pos),16)&128)){tag+=hex.slice(pos,pos+2);pos+=2}if(pos+2>hex.length)break;const first=parseInt(hex.slice(pos,pos+2),16);pos+=2;let len=first;if(first&128){const count=first&127;if(!count||pos+count*2>hex.length)break;len=parseInt(hex.slice(pos,pos+count*2),16);pos+=count*2}const value=hex.slice(pos,pos+len*2);if(value.length!==len*2)break;pos+=len*2;rows.push({tag,length:len,value})}return rows}
function bitmapLengthText(n,request,pc){if(n===12)return request?'3':'6';if(n===53)return p2peMode.checked?'1':'2';if(n===56)return request&&!SPECIAL_DE56.has(pc)?'1':'2';const base=FIELDS[n];if(!base)return'-';return String(base[2]);}
function bitmapTypeText(n){const base=FIELDS[n];if(!base)return'LLVAR';if(n===53||n===56)return'LLVAR';return base[1].replace('_DYNAMIC','')}
function formatIso(parsed){const lines=[];if(parsed.length)lines.push(`Length: ${parsed.length}`);lines.push(`TPDU: ${parsed.tpdu}`,`MTI: ${parsed.mti}`,`Bitmap: ${parsed.bitmapHex}`,'','Data Elements of Bitmap');const rows=$('originalOrder').checked?parsed.rows:[...parsed.rows].sort((a,b)=>a.n-b.n),convert=$('convertAscii').checked,showLength=$('showLength').checked,showFieldName=$('showFieldName').checked,hideValue=$('hideValue').checked;for(const r of rows){const isLlvar=r.type==='LLVAR'||r.type==='LLVAR_DYNAMIC';const converted=convert&&!window.ignoredConvertToAsciiList?.includes(r.n);const value=hideValue?'********':(converted?ascii(r.valueHex):r.valueHex);const displayValue=hideValue?value:(isLlvar?`${r.lengthHex||''}${converted?' ':''}${value}`:value);const number=String(r.n).padEnd(4,' '),fieldName=showFieldName?`(${r.name}) `:'',lengthText=showLength?`(${r.lengthInfo}) `:'';lines.push(`${number}${fieldName}${lengthText}= ${displayValue}`)}if(parsed.error)lines.push('',`Invalid packet: ${parsed.error}`);else if(parsed.remaining)lines.push('',`Unparsed trailing data: ${parsed.remaining}`);return lines.join('\n')}
window.formatIso=formatIso;
function formatBitmap(parsed){const lines=[];if(parsed.length)lines.push(`Length: ${parsed.length}`);lines.push(`TPDU: ${parsed.tpdu}`,`MTI: ${parsed.mti}`,`Bitmap: ${parsed.bitmapHex}`,'','DE    Type    Length    Field Name');const request=state.mode==='request';const pc=parsed.processingCode||'';parsed.active.filter(n=>n!==1).forEach(n=>{const[name]=fieldInfo(n,request,pc);const type=bitmapTypeText(n);const length=bitmapLengthText(n,request,pc);lines.push(`${String(n).padEnd(6,' ')}${type.padEnd(14,' ')}${String(length).padEnd(10,' ')}${name}`)});if(parsed.error)lines.push('',`Invalid packet: ${parsed.error}`);else if(parsed.remaining)lines.push('',`Unparsed trailing data: ${parsed.remaining}`);return lines.join('\n')}
function doParse(){if(state.mode==='de'&&window.DEParser?.parseAndRender){window.DEParser.parseAndRender();return}const hex=cleanHex(input.value);output.classList.remove('error');if(!hex){output.textContent=state.mode==='tlv'?'No TLV data.':'Please enter valid Hex code';return}if(!validHex(hex)){output.textContent='Invalid Hex code';output.classList.add('error');return}try{if(state.mode==='tlv'){const rows=parseTlv(hex);output.textContent=rows.map(r=>`${r.tag} [${r.length}] ${$('convertAscii').checked?ascii(r.value):r.value}`).join('\n')||'No valid TLV data';packetTitle.textContent='TLV / EMV Result';meta.textContent=`${hex.length/2} bytes`;return}const parsed=parseIso(hex,state.mode==='response');packetTitle.textContent='ISO8583 Result';meta.textContent=`MTI ${parsed.mti} · ${parsed.active.filter(n=>n!==1).length} active data fields · ${hex.length/2} bytes${parsed.processingCode?' · PC '+parsed.processingCode:''}`;output.textContent=$('showBitmap').checked?formatBitmap(parsed):formatIso(parsed);if(parsed.error)output.classList.add('error')}catch(e){output.textContent=`Invalid packet: ${e.message||String(e)}`;output.classList.add('error')}}
window.doParse=doParse;window.exactAndroidParse=doParse;window.__androidParserVersion='partial-error-reporting';
function inputKey(mode){return mode==='tlv'?'tlv':mode==='de'?'de':'iso'}
function switchParserInput(mode){const currentKey=inputKey(state.mode),nextKey=inputKey(mode);if(input)state.inputs[currentKey]=input.value;if(input){input.value=state.inputs[nextKey]||'';input.dispatchEvent(new Event('input',{bubbles:true}));}state.mode=mode;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));}
window.switchParserInput=switchParserInput;
function copyResult(){const text=output?.textContent||'';if(!text)return;const done=()=>{const b=$('copyBtn');if(b){const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1000)}};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>fallbackCopy(text,done));else fallbackCopy(text,done)}
function fallbackCopy(text,done){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.focus();ta.select();try{document.execCommand('copy');done()}finally{ta.remove()}}
let autoParseTimer;
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('parseBtn')?.addEventListener('click',doParse);$('clearBtn')?.addEventListener('click',()=>{input.value='';state.inputs[inputKey(state.mode)]='';output.textContent='Enter a packet and click Parse.'});$('copyBtn')?.addEventListener('click',copyResult);['showBitmap','showFieldName','showLength','convertAscii','hideValue','originalOrder','p2peMode'].forEach(id=>$(id)?.addEventListener('change',doParse));input?.addEventListener('input',()=>{state.inputs[inputKey(state.mode)]=input.value;clearTimeout(autoParseTimer);autoParseTimer=setTimeout(doParse,300)})});
function setMode(mode){switchParserInput(mode);doParse()}
