(() => {
  const STORAGE_KEY='bitmapParser.customIsoFields.v1';
  const getFields=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}};
  const saveFields=f=>localStorage.setItem(STORAGE_KEY,JSON.stringify(f));
  const originalFieldInfo=window.fieldInfo;
  window.fieldInfo=function(fieldNo,isReq,processingCode=''){const saved=getFields()[isReq?'request':'response']||{},custom=saved[String(fieldNo)];if(custom)return[custom.name||`Field ${fieldNo}`,custom.type,Number(custom.len)||2];return originalFieldInfo(fieldNo,isReq,processingCode)};
  function injectStyles(){if(document.getElementById('customFieldStyles'))return;const style=document.createElement('style');style.id='customFieldStyles';style.textContent=`
    .iso-fields-modal{position:fixed;inset:0;background:rgba(0,0,0,.55);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.iso-fields-modal.open{display:flex}.iso-fields-card{width:min(1000px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:14px;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.iso-fields-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:10px}.iso-fields-head h2{margin:0}.iso-fields-head p{margin:4px 0 0;color:#667085;font-size:12px}.iso-field-legend{display:flex;gap:18px;font-size:12px;margin:0 0 14px;color:#475467;flex-wrap:wrap}.iso-field-legend span{display:inline-flex;align-items:center;gap:6px}.iso-field-legend i{width:10px;height:10px;border-radius:50%;display:inline-block}.iso-current-dot{background:#667085}.iso-new-dot{background:#16a34a}.iso-mod-dot{background:#2563eb}.field-form{display:grid;grid-template-columns:90px 1fr 120px 110px auto;gap:8px;align-items:end;margin-bottom:18px}.field-form label{font-size:12px;font-weight:600}.field-form input,.field-form select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #ccd2d8;border-radius:7px;margin-top:4px}.field-list{display:flex;flex-direction:column;gap:5px}.iso-field-row{display:grid;grid-template-columns:62px minmax(240px,1fr) 145px 75px 115px;gap:12px;align-items:center;padding:11px 14px;border:1px solid #e3e7ec;border-radius:8px;background:#fafbfc;min-height:42px}.iso-field-row:hover{background:#f5f7fa}.iso-field-row.new{background:#f0fdf4;border-color:#86efac}.iso-field-row.modified{background:#eff6ff;border-color:#93c5fd}.iso-de{font-weight:700;font-size:13px;color:#344054}.iso-name{font-size:13px;color:#1d2939;white-space:normal}.iso-type,.iso-len{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:#475467}.iso-status{text-align:right;font-size:10px;font-weight:800;letter-spacing:.3px}.iso-status.current{color:#667085}.iso-status.new{color:#15803d}.iso-status.modified{color:#1d4ed8}.iso-list-header{display:grid;grid-template-columns:62px minmax(240px,1fr) 145px 75px 115px;gap:12px;padding:7px 14px;color:#667085;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.5px}.iso-list-header span:last-child{text-align:right}.empty-fields{color:#777;padding:12px 0}.settings-tabs{display:flex;gap:6px;margin-bottom:14px}.settings-tab{border:1px solid #ccd2d8;background:#f6f7f8;border-radius:7px;padding:7px 12px;cursor:pointer}.settings-tab.active{background:#e8eef8}@media(max-width:700px){.field-form{grid-template-columns:1fr 1fr}.iso-list-header{display:none}.iso-field-row{grid-template-columns:55px minmax(150px,1fr) 100px 55px 95px;gap:7px;padding:9px}.iso-fields-card{padding:15px}}
  `;document.head.appendChild(style)}
  const builtInFields=()=>window.FIELDS||{};
  function statusFor(no,c){const b=builtInFields()[String(no)]||builtInFields()[no];if(!b)return'new';return b[0]===c.name&&b[1]===c.type&&Number(b[2])===Number(c.len)?'current':'modified'}
  function openSettings(){injectStyles();let modal=document.getElementById('isoFieldsModal');if(!modal){modal=document.createElement('div');modal.id='isoFieldsModal';modal.className='iso-fields-modal';modal.innerHTML=`<div class="iso-fields-card"><div class="iso-fields-head"><div><h2>ISO Field Settings</h2><p>Current ISO fields and your custom changes.</p></div><button id="isoFieldsClose" class="secondary">Close</button></div><div class="iso-field-legend"><span><i class="iso-current-dot"></i> Current</span><span><i class="iso-new-dot"></i> Newly Added</span><span><i class="iso-mod-dot"></i> Modified</span></div><div class="settings-tabs"><button class="settings-tab active" data-side="request">Request</button><button class="settings-tab" data-side="response">Response</button></div><div class="field-form"><label>Field No<input id="cfNo" type="number" min="1" max="128"></label><label>Field Name<input id="cfName" type="text" placeholder="Custom field"></label><label>Type<select id="cfType"><option value="BCD">BCD</option><option value="LLVAR">LLVAR</option><option value="BYTE">BYTE</option></select></label><label id="cfLenLabel">Length<input id="cfLen" type="number" min="1" max="999"></label><button id="cfAdd" class="primary">Add / Modify</button></div><div class="iso-list-header"><span>Field</span><span>Name</span><span>Format</span><span>Length</span><span>Status</span></div><div id="customFieldList" class="field-list"></div><div style="display:flex;justify-content:flex-end;margin-top:14px"><button id="cfReset" class="secondary">Reset Custom Fields</button></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal.querySelector('#isoFieldsClose').onclick=()=>modal.classList.remove('open');modal.querySelectorAll('.settings-tab').forEach(tab=>tab.onclick=()=>{modal.querySelectorAll('.settings-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');renderList(tab.dataset.side)});modal.querySelector('#cfType').onchange=updateLengthLabel;modal.querySelector('#cfAdd').onclick=addField;modal.querySelector('#cfReset').onclick=()=>{const f=getFields();delete f[currentSide()];saveFields(f);renderList(currentSide());if(window.doParse)window.doParse()}}modal.classList.add('open');renderList(currentSide())}
  function currentSide(){return document.querySelector('#isoFieldsModal .settings-tab.active')?.dataset.side||'request'}
  function updateLengthLabel(){document.getElementById('cfLenLabel').firstChild.textContent=document.getElementById('cfType').value==='LLVAR'?'Length Digits':'Length Bytes'}
  function addField(){const no=Number(document.getElementById('cfNo').value),name=document.getElementById('cfName').value.trim(),type=document.getElementById('cfType').value,len=Number(document.getElementById('cfLen').value);if(!no||no<1||no>128||!name||!len){alert('Enter valid Field No, Field Name and Length.');return}const f=getFields();f[currentSide()]||={};f[currentSide()][String(no)]={name,type,len};saveFields(f);renderList(currentSide());if(window.doParse)window.doParse();document.getElementById('cfNo').value='';document.getElementById('cfName').value='';document.getElementById('cfLen').value=''}
  function renderList(side){const list=document.getElementById('customFieldList');if(!list)return;const custom=getFields()[side]||{},base=builtInFields(),nos=new Set([...Object.keys(base),...Object.keys(custom)]),entries=[...nos].map(Number).sort((a,b)=>a-b);if(!entries.length){list.innerHTML='<div class="empty-fields">No ISO fields configured.</div>';return}list.innerHTML=entries.map(no=>{const key=String(no),c=custom[key],b=base[key]||base[no];if(c){const s=statusFor(no,c);return`<div class="iso-field-row ${s}"><span class="iso-de">DE ${no}</span><span class="iso-name">${escapeHtml(c.name)}</span><span class="iso-type">${c.type}</span><span class="iso-len">${c.len}</span><span class="iso-status ${s}">${s==='new'?'NEW':s==='modified'?'MODIFIED':'CURRENT'} <button class="secondary" data-delete="${no}">Delete</button></span></div>`}return`<div class="iso-field-row current"><span class="iso-de">DE ${no}</span><span class="iso-name">${escapeHtml(b[0])}</span><span class="iso-type">${b[1]}</span><span class="iso-len">${b[2]}</span><span class="iso-status current">CURRENT</span></div>`}).join('');list.querySelectorAll('[data-delete]').forEach(btn=>btn.onclick=()=>{const f=getFields();delete f[side]?.[btn.dataset.delete];saveFields(f);renderList(side);if(window.doParse)window.doParse()})}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  window.addEventListener('DOMContentLoaded',()=>{const header=document.querySelector('.topbar');const button=document.createElement('button');button.className='secondary';button.textContent='ISO Fields';button.onclick=openSettings;header?.appendChild(button);const p2pe=document.getElementById('p2peMode');if(p2pe)p2pe.checked=localStorage.getItem('bitmapParser.p2pe')==='true';p2pe?.addEventListener('change',()=>localStorage.setItem('bitmapParser.p2pe',String(p2pe.checked)))})
})();
