(() => {
  const STORAGE_KEY='bitmapParser.customIsoFields.v1';
  const getFields=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}};
  const saveFields=f=>localStorage.setItem(STORAGE_KEY,JSON.stringify(f));
  const originalFieldInfo=window.fieldInfo;
  window.fieldInfo=function(fieldNo,isReq,processingCode=''){const saved=getFields()[isReq?'request':'response']||{},custom=saved[String(fieldNo)];if(custom)return[custom.name||`Field ${fieldNo}`,custom.type,Number(custom.len)||2];return originalFieldInfo(fieldNo,isReq,processingCode)};
  function injectStyles(){if(document.getElementById('customFieldStyles'))return;const style=document.createElement('style');style.id='customFieldStyles';style.textContent=`
    .iso-fields-modal{position:fixed;inset:0;background:rgba(0,0,0,.55);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.iso-fields-modal.open{display:flex}.iso-fields-card{width:min(1000px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:14px;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.25)}
    .iso-fields-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:12px}.iso-fields-head h2{margin:0}.iso-fields-head p{margin:4px 0 0;color:#667085;font-size:12px}.iso-field-legend{display:flex;gap:16px;font-size:12px;margin:0 0 14px;color:#475467}.iso-field-legend span{display:inline-flex;align-items:center;gap:5px}.iso-field-legend i{width:9px;height:9px;border-radius:50%;display:inline-block}.iso-current-dot{background:#98a2b3}.iso-new-dot{background:#16a34a}.iso-mod-dot{background:#2563eb}
    .settings-tabs{display:flex;gap:6px;margin-bottom:14px}.settings-tab{border:1px solid #d0d5dd;background:#fff;border-radius:7px;padding:8px 14px;cursor:pointer}.settings-tab.active{background:#182230;color:#fff;border-color:#182230}
    .field-list{display:flex;flex-direction:column;gap:8px}.field-row{display:grid;grid-template-columns:70px minmax(260px,1fr) 130px minmax(190px,260px) minmax(110px,1fr);gap:14px;align-items:center;padding:12px 14px;border:1px solid #e1e5e9;border-radius:10px;background:#f8fafc;min-height:48px}.field-row:hover{background:#f5f7fa}.field-row.new{background:#f0fdf4;border-color:#86efac;border-left:3px solid #16a34a}.field-row.modified{background:#eff6ff;border-color:#93c5fd;border-left:3px solid #2563eb}.field-no{font-weight:700;color:#344054;white-space:nowrap}.field-name{color:#101828;line-height:1.35}.field-type{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#475467;white-space:nowrap}.field-length{color:#344054;font-size:12px;line-height:1.45}.field-length strong{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.field-length .condition-line{display:block;white-space:nowrap}.field-condition{color:#667085;font-size:11px;line-height:1.4}.field-status{font-size:10px;font-weight:800;letter-spacing:.03em;white-space:nowrap}.field-status.current{color:#667085}.field-status.new{color:#15803d}.field-status.modified{color:#1d4ed8}.field-action{margin-left:6px;padding:4px 7px!important;font-size:11px!important}.empty-fields{color:#667085;padding:20px;text-align:center;border:1px dashed #d0d5dd;border-radius:10px}.field-form{display:grid;grid-template-columns:80px 1fr 120px 100px auto;gap:8px;align-items:end;margin:16px 0}.field-form label{font-size:11px;font-weight:700;color:#475467}.field-form input,.field-form select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #ccd2d8;border-radius:7px;margin-top:4px}.iso-fields-footer{display:flex;justify-content:flex-end;margin-top:14px}@media(max-width:800px){.field-row{grid-template-columns:60px minmax(220px,1fr) 120px 180px 100px;min-width:760px}.field-list{overflow-x:auto}.field-form{grid-template-columns:1fr 1fr}.iso-fields-card{padding:16px}}
  `;document.head.appendChild(style)}
  const builtInFields=()=>window.FIELDS||{};
  function fieldDisplay(side,no,b){
    if(no===12)return {name:side==='request'?'Local Transaction Time':'Local Transaction Date Time',type:'BCD',length:side==='request'?'3':'6',condition:''};
    if(no===53)return {name:'CVV / AES PIN Block',type:'LLVAR',length:'',condition:'',lengthLines:['1 (P2PE)','2 (MKSK)']};
    if(no===56)return {name:b?.[0]||'Previous ROC, Date, Time in Reversal case',type:'LLVAR',length:'',condition:'',lengthLines:['2 (982002, 982004, 960321)','1 (Others)']};
    return {name:b?.[0]||`Field ${no}`,type:b?.[1]||'LLVAR',length:String(b?.[2]??2),condition:''};
  }
  function statusFor(side,no,c){const b=builtInFields()[String(no)]||builtInFields()[no];if(!b)return'new';const d=fieldDisplay(side,no,b);return d.name===c.name&&d.type===c.type&&((d.length&&String(d.length)===String(c.len))||(!d.length&&d.lengthLines?.includes(String(c.len))))?'current':'modified'}
  function openSettings(){injectStyles();let modal=document.getElementById('isoFieldsModal');if(!modal){modal=document.createElement('div');modal.id='isoFieldsModal';modal.className='iso-fields-modal';modal.innerHTML=`<div class="iso-fields-card"><div class="iso-fields-head"><div><h2>ISO Field Settings</h2><p>Current ISO fields and your custom changes.</p></div><button id="isoFieldsClose" class="secondary">Close</button></div><div class="iso-field-legend"><span><i class="iso-current-dot"></i> Current</span><span><i class="iso-new-dot"></i> Newly Added</span><span><i class="iso-mod-dot"></i> Modified</span></div><div class="settings-tabs"><button class="settings-tab active" data-side="request">Request</button><button class="settings-tab" data-side="response">Response</button></div><div class="field-form"><label>Field No<input id="cfNo" type="number" min="1" max="128"></label><label>Field Name<input id="cfName" type="text" placeholder="Custom field"></label><label>Type<select id="cfType"><option value="BCD">BCD</option><option value="LLVAR">LLVAR</option><option value="BYTE">BYTE</option></select></label><label id="cfLenLabel">Length<input id="cfLen" type="number" min="1" max="999"></label><button id="cfAdd" class="primary">Add / Modify</button></div><div id="customFieldList" class="field-list"></div><div class="iso-fields-footer"><button id="cfReset" class="secondary">Reset Custom Fields</button></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal.querySelector('#isoFieldsClose').onclick=()=>modal.classList.remove('open');modal.querySelectorAll('.settings-tab').forEach(tab=>tab.onclick=()=>{modal.querySelectorAll('.settings-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');renderList(tab.dataset.side)});modal.querySelector('#cfType').onchange=updateLengthLabel;modal.querySelector('#cfAdd').onclick=addField;modal.querySelector('#cfReset').onclick=()=>{const f=getFields();delete f[currentSide()];saveFields(f);renderList(currentSide());if(window.doParse)window.doParse()}}modal.classList.add('open');renderList(currentSide())}
  function currentSide(){return document.querySelector('#isoFieldsModal .settings-tab.active')?.dataset.side||'request'}
  function updateLengthLabel(){document.getElementById('cfLenLabel').firstChild.textContent=document.getElementById('cfType').value==='LLVAR'?'Length Digits':'Length Bytes'}
  function addField(){const no=Number(document.getElementById('cfNo').value),name=document.getElementById('cfName').value.trim(),type=document.getElementById('cfType').value,len=Number(document.getElementById('cfLen').value);if(!no||no<1||no>128||!name||!len){alert('Enter valid Field No, Field Name and Length.');return}const f=getFields();f[currentSide()]||={};f[currentSide()][String(no)]={name,type,len};saveFields(f);renderList(currentSide());if(window.doParse)window.doParse();document.getElementById('cfNo').value='';document.getElementById('cfName').value='';document.getElementById('cfLen').value=''}
  function renderList(side){const list=document.getElementById('customFieldList');if(!list)return;const custom=getFields()[side]||{},base=builtInFields(),nos=new Set([...Object.keys(base),...Object.keys(custom)]),entries=[...nos].map(Number).sort((a,b)=>a-b);if(!entries.length){list.innerHTML='<div class="empty-fields">No ISO fields configured.</div>';return}list.innerHTML=entries.map(no=>{const key=String(no),c=custom[key],b=base[key]||base[no],d=fieldDisplay(side,no,b);if(c){const s=statusFor(side,no,c);return`<div class="field-row ${s}"><span class="field-no">DE ${no}</span><span class="field-name">${escapeHtml(c.name)}</span><span class="field-type">${escapeHtml(c.type)}</span><span class="field-length"><strong>${escapeHtml(c.len)}</strong>${d.lengthLines?d.lengthLines.map(x=>`<span class="condition-line">${escapeHtml(x)}</span>`).join(''):''}</span><span class="field-status ${s}">${s==='new'?'NEW':s==='modified'?'MODIFIED':'CURRENT'} <button class="secondary field-action" data-delete="${no}">Delete</button></span></div>`}return`<div class="field-row current"><span class="field-no">DE ${no}</span><span class="field-name">${escapeHtml(d.name)}</span><span class="field-type">${escapeHtml(d.type)}</span><span class="field-length">${d.lengthLines?d.lengthLines.map(x=>`<span class="condition-line">${escapeHtml(x)}</span>`).join(''): `<strong>${escapeHtml(d.length)}</strong>`}</span><span class="field-status current">CURRENT</span></div>`}).join('');list.querySelectorAll('[data-delete]').forEach(btn=>btn.onclick=()=>{const f=getFields();delete f[side]?.[btn.dataset.delete];saveFields(f);renderList(side);if(window.doParse)window.doParse()})}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  window.addEventListener('DOMContentLoaded',()=>{const header=document.querySelector('.topbar');const button=document.createElement('button');button.className='secondary';button.textContent='ISO Fields';button.onclick=openSettings;header?.appendChild(button);const p2pe=document.getElementById('p2peMode');if(p2pe){p2pe.checked=true;p2pe.removeAttribute('checked');p2pe.checked=true}})
})();
